print("Hello World")
print('Hello, Hyuga')
print("Hello, Ryodai")
print("Hello, miyachi")
print('Reviewers PoC')
print('by GUI')
print('practice')
print('hello, hyuga0202')
print('aaa')
print('Hello, Shoji!0101')
print('aaaaaaaa')
print('conflict test')
print('********DOES IT CONFLICT?*******')
