print("Hello World")
print('Hello, Hyuga030303')
print("Hello, Ryodai")
print("Hello, miyachi")
print('Reviewers PoC')
print('by GUI')
print('practice')
print('hello, hyuga010101')
print('hello, hyuga020202')
print('aaa')
print('Hello, Shoji!010101')
print('aaaaaaaa')
print('conflict test')
print('********DOES IT CONFLICT?*******')
